### PR TITLE
Allow passing a predicate to skip protection on requests

### PR DESCRIPTION
**Pull request by glittershark**
Allow passing a `skip-request?`predicate that will cause CSRF protection
to be skipped if it returns true.

I considered eliminating the `(not (get-request?))` check here and just
defaulting `skip-request?` to `get-request?`; let me know if that's
what you'd like to do instead of this

### CODE REVIEW

**Comment by weavejester** [comment]
Why not just selectively apply the middleware?

**Comment by glittershark** [comment]
I guess I could do that, yeah. This feels more elegant, though, and has the advantage of being able to pass options straight to `ring-defaults`.

**Comment by weavejester** [comment]
I don't really like the idea of adding functionality to middleware that could instead be implemented without changing the middleware. The anti-forgery middleware could be applied directly, or wrapped in another function that selectively applies it based on a predicate. I don't think this functionality needs to be tied to ring-anti-forgery, when the same result can be achieved with a more general function.

**Comment by glittershark** [comment]
That's fair! thanks for the quick response and for being so decisive

**Comment by weavejester** [comment]
To give you an example of what I mean:

```clojure
(defn wrap-middleware-if [handler predicate middleware]
  (let [handler-with-middleware (middleware handler)]
    (fn [request]
      (if (predicate request)
        (handler-with-middleware request)
        (handler request)))))
```

**Comment by glittershark** [comment]
👍

**Pull request closed without merging**
