### PR TITLE
add encrypted token pattern to `wrap-anti-forgery`-middleware

### PR DESCRIPTION
**Pull request by chrisbetz**
Hi James,

I added support for the encrypted token pattern in order to mitigate the risk for CSRF attacks on stateless servers (see https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Encrypted_Token_Pattern).

Hope everything is clear and in a way you expect things to be:
- documented new things in README
- added tests, hopefully clear enough to understand
- as far as I can tell, this does not break existing code from Clojure 1.7 onwards

There's a breaking change: As I had to introduce new dependencies for JWT-encryption, I had to drop support for Clojure 1.5.1 and 1.6.

Thus, maybe a new major release is in order? However, that's up to you.

Happy if you decide to merge the PR, otherwise also happy to hear your comments on that.

Happy hacking,

Chris

---
This change is [Reviewable](https://reviewable.io/reviews/ring-clojure/ring-anti-forgery/16)

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch!

Why are you using assymetric encryption for the token? It seems to me that the Buddy dependencies are unnecessary if symmetric encryption with a HMAC is used instead.

I've created a draft [CONTRIBUTING](https://github.com/weavejester/contributing/blob/master/CONTRIBUTING.md) guideline that I plan to add to my repos once I'm happy with the wording. Could you ensure that your patch follows the guideline?

Could you also remove all the indentation changes in your commit? I guess your editor is automatically formatting things, but it's removing whitespace that aligns forms.

**Comment by chrisbetz** [comment]
Hi James,

thanks for the fast feedback :) I applied the changes to remove the indentation changes. Sorry for that, I usually diff without whitspaces, so I didn't notice.

As far as I can tell, I'm following your CONTRIBUTING guideline. Glad you have some!

Concerning the choice of assymetric encryption instead of symmetric - it just "fits" my use of authentication tokens in the rest of my code.

However, I could think of other combinations of options:
- if only public-key and private-key are given, I could use these to also sign the token for verification  (no need for secret option)
- if only secret option is given, I could use symmetric encryption.

To me, these are two new features I'm not using currently and which would make sense to create in e separate PR anyhow. So I really hope you accept the new dependency... Happy to hear about your thoughts!

Sincerly

Chris

**Comment by chrisbetz** [comment]
... thought a little about it.

I've two more things to say:
- regarding asymmetric signing/encryption: In my use-case, it may occur that generation (public key) of the CSRF-Token and verification (private key) are residing in two different services.

- if you decide on having a major release anyhow, there's something to consider: Right now, a new token is generated on every request and provided as *anti-forgery-token*. With encryption, this will cost some energy. I personally think it would be better to refactor that to a more "on demand" approach or to separate the "anti-forgery-token-generation"-middleware and the "anti-forgery-token-check" middleware.

However, the latter is definitively more than I would go for in a single PR. It's more like I would release a 2.0.0-alpha1 to move on from there. I'm more than willing to help you on that refactoring/development, if you're not having the time for this to come up with a final 2.0.0 release with all the features sketched above. For the moment, I'd be glad to see this PR being accepted ;)

Again, happy hacking!

Chris

**Comment by weavejester** [comment]
My inclination is not to use Buddy or public key encryption for this. It adds an additional dependency that isn't necessary, and symmetric encryption with a HMAC is more efficient anyway.

It strikes me that encrypting the token works out to be the same as using encrypted cookie sessions in Ring. The only thing it lacks is a stored timestamp and expiry, which would be a good thing to add in generally. So my suggestion is that we first add a timestamp and expiry, then think about whether it's necessary to add encrypted tokens in, or if we just piggyback off cookie session instead.

**Comment by chrisbetz** [comment]
I'm on it, will come back to this soon.
- Protocol: You name it, that's a good idea.
- Encrypting the token same as cookie-session: Yeees, but you must not store the CSRF-token into a cookie if you store your authentication in some kind of cookie. Instead, we need the separation of storage/transport (one accessible from Java/ClojureScript, HTML forms, etc.) and one sent along the requests automatically (i.e. initiated by the browser). But yes, both could rely on JWT, so maybe it's a good idea to move cookie sessions to JWT (see jwt.io).
- using symmetric encryption: yes, easier
- using asymmeric encryption/signing: yes, allows separation of token-issuer and token-verifier with no shared secret.

Pls stay tuned.

**Comment by weavejester** [comment]
> Encrypting the token same as cookie-session: Yeees, but you must not store the CSRF-token into a cookie if you store your authentication in some kind of cookie.

Sorry, I don't follow. Why not?

**Comment by chrisbetz** [comment]
Hi...

sorry, this needs some more love (both on the code/security side) and on the discussion side. So I'd like to close this PR first and come back later to you with a clean solution for this (to not bother you with each commit on this branch).

I really enjoy your feedback and it definitively makes the code better - and again: security is really hard to get right ;)

Will keep you posted.

Sincerly,

Chris

**Pull request closed without merging**
